# Generated by Django 3.2.14 on 2022-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('author', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('read_time', models.IntegerField()),
            ],
        ),
    ]
