# Generated by Django 3.2.14 on 2022-07-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
